(car '(apple banana cake))
(car '(("dog" "cat")"fish"))
(caar '(("dog" "cat")"fish"))
(caadr  '((a b)(c d)(e f)))
(cadar '((x y z)a b))
(cdr '(a b c))
(cdar '((1 2 3)4 5))
(cdr '((a b)(c d)(e f)))
(cddar '((a b c)d e))
(cdr '((x y)(z w)))

